# Generated by Django 2.1.4 on 2019-07-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
