# Generated by Django 2.2.3 on 2019-07-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshopapp', '0004_auto_20190703_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='gshopapp.CartItem'),
        ),
    ]
