# Generated by Django 2.2.3 on 2019-07-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshopapp', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buing_type',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], default='Pickup', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In processing', 'In processing'), ('Performed', 'Performed'), ('Paid', 'Paid')], default='In processing', max_length=64),
        ),
    ]
